name: Avito → Google Sheets stats

on:
  workflow_dispatch:      # запуск вручную в Actions
  schedule:
    - cron: "0 5 * * *"   # каждый день в 08:00 МСК (5:00 UTC)
                          # если не нужно авто — закомментируй

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread oauth2client

      - name: Run Avito stats script
        env:
          AVITO_CLIENT_ID: ${{ secrets.AVITO_CLIENT_ID }}
          AVITO_CLIENT_SECRET: ${{ secrets.AVITO_CLIENT_SECRET }}
          AVITO_USER_ID: ${{ secrets.AVITO_USER_ID }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
          ITEM_IDS_CSV: ${{ secrets.ITEM_IDS_CSV }}   # можно не задавать
        run: |
          python avito_to_sheets.py
