name: Avito Stats Daily

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 5 * * *"   # каждый день в 05:00 UTC (~08:00 МСК)

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
