name: Avito Stats Daily

on:
  workflow_dispatch:   # запуск вручную
  schedule:
    - cron: "0 5 * * *"   # каждый день в 05:00 UTC (~08:00 МСК)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread oauth2client

           - name: Debug: show repo and file
        run: |
          pwd
          ls -la
          echo "---- file head ----"
          sed -n '1,120p' avito_to_sheets.py || true
          echo "---- end head ----"

      - name: Run Avito to Sheets (unbuffered)
        env:
          AVITO_CLIENT_ID: ${{ secrets.AVITO_CLIENT_ID }}
          AVITO_CLIENT_SECRET: ${{ secrets.AVITO_CLIENT_SECRET }}
          AVITO_USER_ID: ${{ secrets.AVITO_USER_ID }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
          ITEM_IDS_CSV: ${{ secrets.ITEM_IDS_CSV }}
        run: python -u avito_to_sheets.py
